# Generated by Django 4.0.1 on 2022-02-11 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensationinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, db_column='Currency', max_length=10, null=True)),
                ('basic', models.IntegerField(blank=True, db_column='Basic', null=True)),
                ('dearnessallowance', models.IntegerField(blank=True, db_column='DearnessAllowance', null=True)),
                ('hra', models.IntegerField(blank=True, db_column='HRA', null=True)),
                ('conveyanceallowance', models.IntegerField(blank=True, db_column='ConveyanceAllowance', null=True)),
                ('specialallowance', models.IntegerField(blank=True, db_column='SpecialAllowance', null=True)),
                ('salaryadvance', models.IntegerField(blank=True, db_column='SalaryAdvance', null=True)),
                ('pfemployee', models.IntegerField(blank=True, db_column='PFEmployee', null=True)),
                ('esicemployee', models.IntegerField(blank=True, db_column='ESICEmployee', null=True)),
                ('pt', models.IntegerField(blank=True, db_column='PT', null=True)),
                ('pfemployercont', models.IntegerField(blank=True, db_column='PFEmployerCont', null=True)),
                ('esicemployercont', models.IntegerField(blank=True, db_column='ESICEmployerCont', null=True)),
                ('iseffective', models.IntegerField(blank=True, db_column='IsEffective', null=True)),
                ('effectivestartdate', models.DateField(blank=True, db_column='EffectiveStartDate', null=True)),
                ('effectiveenddate', models.DateField(blank=True, db_column='EffectiveEndDate', null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
                ('lastupdatedby', models.CharField(blank=True, db_column='LastUpdatedBy', max_length=10, null=True)),
                ('lastupdateddate', models.DateField(blank=True, db_column='LastUpdatedDate', null=True)),
                ('empid', models.ForeignKey(blank=True, db_column='EmpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.employee')),
            ],
        ),
    ]
