# Generated by Django 4.0.1 on 2022-02-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0002_compensationinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compensationinfo',
        ),
    ]
