# Generated by Django 4.0.1 on 2022-02-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hr', '0005_delete_compensationinfo_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(db_column='EmpId', max_length=10, primary_key=True, serialize=False)),
                ('effectivestartdate', models.DateField(blank=True, db_column='EffectiveStartDate', null=True)),
                ('effectiveenddate', models.DateField(blank=True, db_column='EffectiveEndDate', null=True)),
                ('lastupdatedby', models.CharField(blank=True, db_column='LastUpdatedBy', max_length=10, null=True)),
                ('lastupdateddate', models.DateField(blank=True, db_column='LastUpdatedDate', null=True)),
                ('hiredate', models.DateField(blank=True, db_column='HireDate', null=True)),
                ('oktorehire', models.CharField(blank=True, db_column='OkToRehire', max_length=10, null=True)),
                ('terminationdate', models.DateField(blank=True, db_column='TerminationDate', null=True)),
                ('benefitsstartdate', models.DateField(blank=True, db_column='BenefitsStartDate', null=True)),
                ('benefitsenddate', models.DateField(blank=True, db_column='BenefitsEndDate', null=True)),
                ('iseffective', models.IntegerField(blank=True, db_column='IsEffective', null=True)),
                ('totalyearsofexperience', models.CharField(blank=True, db_column='TotalYearsOfExperience', max_length=10, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
            ],
        ),
    ]
