# Generated by Django 4.0.1 on 2022-02-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0009_compensationinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compensationinfo',
        ),
    ]
