# Generated by Django 4.0.1 on 2022-03-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0012_delete_personalinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employee1',
        ),
    ]
