# Generated by Django 4.0.1 on 2022-03-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0013_rename_employee_employee1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.CharField(blank=True, db_column='PhoneNo', max_length=10, null=True)),
                ('phonetype', models.CharField(blank=True, db_column='PhoneType', max_length=10, null=True)),
                ('countrycode', models.CharField(blank=True, db_column='CountryCode', max_length=10, null=True)),
                ('extension', models.CharField(blank=True, db_column='Extension', max_length=10, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
                ('lastupdatedby', models.CharField(blank=True, db_column='LastUpdatedBy', max_length=10, null=True)),
                ('lastupdateddate', models.DateField(blank=True, db_column='LastUpdatedDate', null=True)),
                ('addresstype', models.CharField(blank=True, db_column='AddressType', max_length=10, null=True)),
                ('address1', models.CharField(blank=True, db_column='Address1', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=10, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=10, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=10, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=10, null=True)),
                ('iseffective', models.IntegerField(blank=True, db_column='IsEffective', null=True)),
                ('effectivestartdate', models.DateField(blank=True, db_column='EffectiveStartDate', null=True)),
                ('effectiveenddate', models.DateField(blank=True, db_column='EffectiveEndDate', null=True)),
                ('empid', models.ForeignKey(blank=True, db_column='EmpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.employee1')),
            ],
        ),
    ]
