# Generated by Django 4.0.1 on 2022-03-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0014_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact1',
        ),
    ]
