# Generated by Django 4.0.1 on 2022-03-07 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0016_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousorgname', models.CharField(blank=True, db_column='PreviousOrgName', max_length=10, null=True)),
                ('startperiod', models.CharField(blank=True, db_column='StartPeriod', max_length=10, null=True)),
                ('endperiod', models.CharField(blank=True, db_column='EndPeriod', max_length=10, null=True)),
                ('yearsofexperience', models.IntegerField(blank=True, db_column='yearsOfExperience', null=True)),
                ('referencename', models.CharField(blank=True, db_column='ReferenceName', max_length=10, null=True)),
                ('referencecontact', models.CharField(blank=True, db_column='ReferenceContact', max_length=10, null=True)),
                ('empid', models.ForeignKey(blank=True, db_column='EmpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.employee1')),
            ],
        ),
    ]
