# Generated by Django 4.0.1 on 2022-03-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0017_experience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='Experience1',
        ),
    ]
