# Generated by Django 4.0.1 on 2022-03-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0018_rename_experience_experience1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobinfo',
            fields=[
                ('personid', models.CharField(db_column='PersonId', max_length=10, primary_key=True, serialize=False)),
                ('jobname', models.CharField(blank=True, db_column='JobName', max_length=10, null=True)),
                ('employeecclass', models.CharField(blank=True, db_column='EmployeecClass', max_length=10, null=True)),
                ('employeetype', models.CharField(blank=True, db_column='EmployeeType', max_length=10, null=True)),
                ('employeestatus', models.CharField(blank=True, db_column='EmployeeStatus', max_length=10, null=True)),
                ('jobstartdate', models.DateField(blank=True, db_column='JobStartDate', null=True)),
                ('positionstartdate', models.DateField(blank=True, db_column='PositionStartDate', null=True)),
                ('isfulltimeemployee', models.IntegerField(blank=True, db_column='IsFulltimeEmployee', null=True)),
                ('jobtitle', models.CharField(blank=True, db_column='JobTitle', max_length=10, null=True)),
                ('position', models.CharField(blank=True, db_column='Position', max_length=10, null=True)),
                ('positionname', models.CharField(blank=True, db_column='PositionName', max_length=10, null=True)),
                ('standardhours', models.CharField(blank=True, db_column='StandardHours', max_length=10, null=True)),
                ('costcenter', models.CharField(blank=True, db_column='CostCenter', max_length=10, null=True)),
                ('costcentername', models.CharField(blank=True, db_column='CostCenterName', max_length=10, null=True)),
                ('clientbasedhiredate', models.DateField(blank=True, db_column='ClientBasedHireDate', null=True)),
                ('destination', models.CharField(blank=True, db_column='Destination', max_length=10, null=True)),
                ('empid', models.ForeignKey(blank=True, db_column='EmpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.employee1')),
            ],
        ),
    ]
