# Generated by Django 4.0.1 on 2022-03-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0020_leaveinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managementinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerempid', models.CharField(blank=True, db_column='ManagerEmpId', max_length=10, null=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=10, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=10, null=True)),
                ('workphone', models.CharField(blank=True, db_column='WorkPhone', max_length=10, null=True)),
                ('manageremail', models.CharField(blank=True, db_column='ManagerEmail', max_length=10, null=True)),
                ('iseffective', models.IntegerField(blank=True, db_column='IsEffective', null=True)),
                ('effectivestartdate', models.DateField(blank=True, db_column='EffectiveStartDate', null=True)),
                ('effectiveenddate', models.DateField(blank=True, db_column='EffectiveEndDate', null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
                ('lastupdatedby', models.CharField(blank=True, db_column='LastUpdatedBy', max_length=10, null=True)),
                ('lastupdateddate', models.DateField(blank=True, db_column='LastUpdatedDate', null=True)),
                ('empid', models.ForeignKey(blank=True, db_column='EmpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.employee1')),
            ],
        ),
    ]
