# Generated by Django 4.0.1 on 2022-03-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0021_managementinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalid', models.CharField(blank=True, db_column='NationalId', max_length=10, null=True)),
                ('cardtype', models.CharField(blank=True, db_column='CardType', max_length=10, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
                ('lastupdatedby', models.CharField(blank=True, db_column='LastUpdatedBy', max_length=10, null=True)),
                ('lastupdateddate', models.DateField(blank=True, db_column='LastUpdatedDate', null=True)),
                ('empid', models.ForeignKey(blank=True, db_column='EmpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.employee1')),
            ],
        ),
    ]
