# Generated by Django 4.0.1 on 2022-03-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0022_nationalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationtype', models.CharField(blank=True, db_column='OrganizationType', max_length=10, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=10, null=True)),
                ('company', models.CharField(blank=True, db_column='Company', max_length=10, null=True)),
                ('companycode', models.CharField(blank=True, db_column='CompanyCode', max_length=10, null=True)),
                ('companyname', models.CharField(blank=True, db_column='CompanyName', max_length=10, null=True)),
                ('accountcode', models.CharField(blank=True, db_column='AccountCode', max_length=10, null=True)),
                ('accountbtname', models.CharField(blank=True, db_column='AccountBtName', max_length=10, null=True)),
                ('address1', models.CharField(blank=True, db_column='Address1', max_length=20, null=True)),
                ('address2', models.CharField(blank=True, db_column='Address2', max_length=20, null=True)),
                ('address3', models.CharField(blank=True, db_column='Address3', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=10, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=10, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=10, null=True)),
                ('empid', models.ForeignKey(blank=True, db_column='EmpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.employee1')),
            ],
        ),
    ]
