# Generated by Django 4.0.1 on 2022-03-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0024_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_field', models.CharField(blank=True, db_column='Class', max_length=10, null=True)),
                ('markpercentage', models.IntegerField(blank=True, db_column='MarkPercentage', null=True)),
                ('passoutyear', models.CharField(blank=True, db_column='PassOutYear', max_length=10, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=10, null=True)),
                ('institutionname', models.CharField(blank=True, db_column='InstitutionName', max_length=10, null=True)),
                ('empid', models.ForeignKey(blank=True, db_column='EmpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.employee1')),
            ],
        ),
    ]
