# Generated by Django 4.0.1 on 2022-03-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0025_qualification1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isprimary', models.IntegerField(blank=True, db_column='IsPrimary', null=True)),
                ('technology', models.CharField(blank=True, db_column='Technology', max_length=10, null=True)),
                ('yearsofexperience', models.IntegerField(blank=True, db_column='YearsOfExperience', null=True)),
                ('lastused', models.CharField(blank=True, db_column='LastUsed', max_length=10, null=True)),
                ('certified', models.IntegerField(blank=True, db_column='Certified', null=True)),
                ('empid', models.ForeignKey(blank=True, db_column='EmpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.employee1')),
            ],
        ),
    ]
