# Generated by Django 4.0.1 on 2022-03-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0026_skills1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheetinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekstartdate', models.DateField(blank=True, db_column='WeekStartDate', null=True)),
                ('monday', models.CharField(blank=True, db_column='Monday', max_length=10, null=True)),
                ('sunday', models.CharField(blank=True, db_column='Sunday', max_length=10, null=True)),
                ('empid', models.ForeignKey(blank=True, db_column='EmpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.employee1')),
            ],
        ),
    ]
