# Generated by Django 4.0.1 on 2022-03-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0027_timesheetinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(blank=True, db_column='BankName', max_length=10, null=True)),
                ('branch', models.CharField(blank=True, db_column='Branch', max_length=10, null=True)),
                ('accountnumber', models.CharField(blank=True, db_column='AccountNumber', max_length=10, null=True)),
                ('ifsccode', models.CharField(blank=True, db_column='IFSCCode', max_length=10, null=True)),
                ('beneficiaryname', models.CharField(blank=True, db_column='BeneficiaryName', max_length=10, null=True)),
                ('accounttype', models.CharField(blank=True, db_column='AccountType', max_length=10, null=True)),
                ('routingnumber', models.CharField(blank=True, db_column='RoutingNumber', max_length=10, null=True)),
                ('empid', models.ForeignKey(blank=True, db_column='EmpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.employee1')),
            ],
        ),
    ]
