# Generated by Django 4.0.1 on 2022-02-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProspectCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, max_length=10, null=True, verbose_name='effective start date')),
                ('totalYearsofExp', models.CharField(blank=True, max_length=10, null=True, verbose_name='effective end date')),
                ('releventExp', models.CharField(blank=True, max_length=10, null=True, verbose_name='hire date')),
                ('noticePeriod', models.CharField(blank=True, max_length=1, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='termination date')),
                ('currentCompany', models.CharField(blank=True, max_length=20, null=True, verbose_name='benafit end  date')),
                ('Currentctc', models.IntegerField(default=False)),
                ('expectedCtc', models.IntegerField(default=False)),
                ('currentLoc', models.CharField(blank=True, max_length=20, null=True)),
                ('preferredLoc', models.CharField(blank=True, max_length=20, null=True)),
                ('lastWorkingDay', models.CharField(blank=True, max_length=15, null=True)),
                ('lastUpdatedDate', models.DateField(auto_now=True, verbose_name='last updated  date')),
                ('lastUpdatedBy', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.authuser')),
            ],
        ),
    ]
