# Generated by Django 4.0.1 on 2022-01-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=10)),
                ('Emp_id', models.CharField(max_length=10)),
            ],
        ),
    ]
