# Generated by Django 4.0.1 on 2022-01-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tekhrmsd01db_delete_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tekhrmsd01db',
        ),
    ]
