# Generated by Django 4.0.1 on 2022-01-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0003_delete_tekhrmsd01db'),
    ]

    operations = [
        migrations.CreateModel(
            name='tekhrmsd01db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(max_length=10)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
