# Generated by Django 4.0.1 on 2022-01-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_employee_delete_tekhrmsd01db'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='tekhrmsd01db',
        ),
    ]
