# Generated by Django 4.0.1 on 2022-02-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_employee_tekhrmsd01db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tekhrmsd01db',
        ),
    ]
